"""Localized copy for the public Chief Editor Neko sample hub."""

from __future__ import annotations


_EN = {
    "title": "Chief Editor Neko's Sample Chart | nanamiastro", "description": "Try Chief Editor Neko's sample chart, planner, AI reading, and astrocartography map.",
    "banner": "Demo Version", "banner_body": "This sample uses Chief Editor Neko. Purchase your own Personal Edition to generate your personalized chart.",
    "eyebrow": "Neko's Sample Chart", "name": "Chief Editor Neko", "hero": "Explore the nanamiastro experience using fixed fictional data. Nothing you do here creates or changes a customer Personal Edition.",
    "date": "February 22, 2022 · 10:22 PM", "place": "Yokohama, Japan", "fictional": "Fictional sample data",
    "sample_role": "This is a purchase preview made with fictional data. Chief Editor Neko is not included in any paid download.",
    "acg_title": "ACG Personal Edition", "acg_lead": "Explore Neko's map and sample package. The paid ACG Bundle includes your personalized ACG and a 12-month Planner.", "try_online": "TRY IT ONLINE", "explore_acg": "Explore Neko's ACG", "explore_acg_desc": "Explore Neko's sample lines on the world map before downloading.", "sample_zip": "SAMPLE ZIP", "zip_title": "Personal Edition ACG ZIP", "zip_desc": "Download the localized sample and check its files and README.",
    "planner_title": "Included 12-Month Planner", "planner_lead": "Preview the Planner included with the ACG Bundle and FULL Edition. This page does not sell the paused standalone Planner.", "permanent_demo": "PERMANENT DEMO", "planner_card": "12-Month Planner Preview", "planner_desc": "Every daily AI button and QR code uses Neko's fixed demo URL.", "open_pdf": "Open PDF in a new tab", "save_pdf": "Save PDF", "planner_note": "About 5 MB. The 432-page preview may take a moment to appear.", "daily_tag": "DAILY AI SAMPLE", "daily_title": "Ask AI for This Day", "daily_desc": "Try the read-only daily prompt connected from the planner.",
    "previews_title": "Free Previews", "previews_lead": "Additional free ways to explore this fictional sample.", "available": "AVAILABLE", "birth_chart": "Birth Chart", "birth_chart_desc": "View Neko's sample horoscope wheel.", "ai_page": "AI Page", "ai_page_desc": "Read a short example of an AI interpretation.",
    "chart_tag": "SAMPLE BIRTH CHART", "chart_title": "Chief Editor Neko's Horoscope", "chart_desc": "A complete natal wheel generated from the sample data.", "chart_alt": "Chief Editor Neko sample birth chart",
    "reading_tag": "SAMPLE AI PAGE", "reading_title": "A curious editor with a wide-angle view", "core": "Core voice", "core_body": "Neko notices patterns, follows unusual questions, and turns complex ideas into an inviting story.", "rhythm": "Creative rhythm", "rhythm_body": "Independent exploration works best when balanced with quiet observation and play.", "growth": "Growth theme", "growth_body": "The sample suggests learning through new places, perspectives, and creative tools.", "sample_disclaimer": "This is sample editorial copy, not personal advice or a factual reading about a real animal or person.",
    "locked_title": "Sample only:", "locked": "The downloadable ZIP contains Chief Editor Neko's fictional sample ACG. Customer data, order codes, and raw YAML downloads remain unavailable. The planner and daily prompt are read-only purchase previews, not product files.", "shop": "View personalized editions on Etsy",
}

_JA = {
    **_EN,
    "title": "ねこ編集長のサンプル鑑定 | nanamiastro", "description": "ねこ編集長のサンプル出生図、プランナー、AI鑑定、ACG地図をお試しいただけます。",
    "banner": "デモ版", "banner_body": "ねこ編集長の固定サンプルです。ご自身のPersonal Editionは商品購入後に作成できます。",
    "eyebrow": "ねこ編集長のサンプル鑑定", "name": "ねこ編集長", "hero": "架空の固定データでnanamiastroの体験を確認できます。このページの操作で購入者用Personal Editionが作成・変更されることはありません。",
    "date": "2022年2月22日 22:22", "place": "神奈川県 横浜市", "fictional": "架空のサンプルデータ",
    "sample_role": "架空データを使った購入前サンプルです。ねこ編集長のデータは有料商品の配布物には含まれません。",
    "acg_title": "ACG Personal Edition", "acg_lead": "ねこ編集長の地図とサンプルZIPを確認できます。有料のACG Bundleには、ご本人用ACGと12か月プランナーが含まれます。", "try_online": "オンラインで試す", "explore_acg": "ねこ編集長のACGを見る", "explore_acg_desc": "ダウンロード前に世界地図上のサンプル線を自由に確認できます。", "sample_zip": "サンプルZIP", "zip_title": "Personal Edition ACG ZIP", "zip_desc": "日本語版サンプルのファイルとREADMEを確認できます。",
    "planner_title": "同梱12か月プランナー", "planner_lead": "ACG BundleとFULL版に含まれるプランナーの購入前サンプルです。休止中のプランナー単体商品は、このページでは販売しません。", "permanent_demo": "無期限デモ", "planner_card": "12か月プランナー・プレビュー", "planner_desc": "日別AIボタンとQRコードはねこ編集長の固定デモURLにつながります。", "open_pdf": "新しいタブでPDFを見る", "save_pdf": "PDFを保存", "planner_note": "約5MB・432ページです。表示に少し時間がかかる場合があります。", "daily_tag": "日別AIサンプル", "daily_title": "この日をAIに聞く", "daily_desc": "プランナーからつながる読み取り専用の日別プロンプトを確認できます。",
    "previews_title": "無料プレビュー", "previews_lead": "架空サンプルを確認できる追加プレビューです。", "available": "利用可能", "birth_chart": "出生図", "birth_chart_desc": "サンプルのホロスコープホイールを表示します。", "ai_page": "AI鑑定例", "ai_page_desc": "AI解釈で作れる体験の短い例です。",
    "chart_tag": "サンプル出生図", "chart_title": "ねこ編集長のホロスコープ", "chart_desc": "固定サンプルデータから生成した出生図です。", "chart_alt": "ねこ編集長のサンプル出生図",
    "reading_tag": "AI鑑定サンプル", "reading_title": "広い視野を持つ好奇心旺盛な編集者", "core": "中心の声", "core_body": "ねこ編集長はパターンに気づき、少し変わった問いを追い、複雑な内容を親しみやすい物語にします。", "rhythm": "創造のリズム", "rhythm_body": "自由な探究と、静かな観察や遊びの時間を両立すると力を発揮します。", "growth": "成長テーマ", "growth_body": "新しい場所、視点、創作ツールとの出会いを通して学ぶサンプルです。", "sample_disclaimer": "これは編集用の架空サンプルであり、個人的な助言や実在する人物・動物の鑑定ではありません。",
    "locked_title": "サンプル限定:", "locked": "ダウンロードZIPには、ねこ編集長の架空ACGサンプルだけが含まれます。購入者データ・注文コード・元YAMLは公開されません。プランナーと日別プロンプトも、商品ファイルではなく読み取り専用の購入前サンプルです。", "shop": "パーソナライズ商品を見る",
}

_ES = {
    **_EN,
    "title": "Carta de muestra de Jefa Editora Neko | nanamiastro", "description": "Prueba la carta natal, el planner, la lectura con IA y el mapa de astrocartografía de Jefa Editora Neko.",
    "banner": "Versión de demostración", "banner_body": "Esta muestra utiliza los datos fijos de Jefa Editora Neko. Tras comprar, podrás crear tu propia Edición Personal.",
    "eyebrow": "Carta de muestra de Neko", "name": "Jefa Editora Neko", "hero": "Explora la experiencia nanamiastro con datos ficticios fijos. Nada de lo que hagas aquí crea ni modifica la Edición Personal de un cliente.",
    "date": "22 de febrero de 2022 · 22:22", "place": "Yokohama, Japón", "fictional": "Datos ficticios de muestra", "sample_role": "Esta es una muestra previa a la compra creada con datos ficticios. Los datos de Neko no se incluyen en ninguna descarga de pago.",
    "acg_title": "Edición Personal ACG", "acg_lead": "Explora el mapa y el ZIP de muestra de Neko. El ACG Bundle de pago incluye tu ACG personalizado y un Planner de 12 meses.", "try_online": "PROBAR EN LÍNEA", "explore_acg": "Explorar el ACG de Neko", "explore_acg_desc": "Consulta las líneas de muestra de Neko en el mapa mundial antes de descargar.", "sample_zip": "ZIP DE MUESTRA", "zip_title": "ZIP de la Edición Personal ACG", "zip_desc": "Descarga la muestra en español y revisa sus archivos y el README.",
    "planner_title": "Planner de 12 meses incluido", "planner_lead": "Vista previa del Planner incluido con el ACG Bundle y la Edición FULL. El Planner independiente está pausado y no se vende desde esta página.", "permanent_demo": "DEMO PERMANENTE", "planner_card": "Vista previa del Planner de 12 meses", "planner_desc": "Cada botón y código QR de IA diaria utiliza la URL fija de demostración de Neko.", "open_pdf": "Abrir PDF en una pestaña nueva", "save_pdf": "Guardar PDF", "planner_note": "Aproximadamente 5 MB y 432 páginas. La vista previa puede tardar en aparecer.", "daily_tag": "MUESTRA DE IA DIARIA", "daily_title": "Consultar este día con IA", "daily_desc": "Prueba el prompt diario de solo lectura enlazado desde el Planner.",
    "previews_title": "Vistas previas gratuitas", "previews_lead": "Otras formas gratuitas de explorar esta muestra ficticia.", "available": "DISPONIBLE", "birth_chart": "Carta natal", "birth_chart_desc": "Consulta la rueda natal de muestra de Neko.", "ai_page": "Página de IA", "ai_page_desc": "Lee un breve ejemplo de interpretación con IA.",
    "chart_tag": "CARTA NATAL DE MUESTRA", "chart_title": "Horóscopo de Jefa Editora Neko", "chart_desc": "Una rueda natal completa generada con los datos de muestra.", "chart_alt": "Carta natal de muestra de Jefa Editora Neko",
    "reading_tag": "MUESTRA DE LECTURA CON IA", "reading_title": "Una editora curiosa con una mirada amplia", "core": "Voz esencial", "core_body": "Neko detecta patrones, sigue preguntas poco habituales y convierte ideas complejas en una historia cercana.", "rhythm": "Ritmo creativo", "rhythm_body": "La exploración independiente funciona mejor cuando se equilibra con observación tranquila y juego.", "growth": "Tema de crecimiento", "growth_body": "La muestra sugiere aprender mediante lugares, perspectivas y herramientas creativas nuevas.", "sample_disclaimer": "Este es un texto editorial ficticio, no un consejo personal ni una lectura factual sobre una persona o animal real.",
    "locked_title": "Solo muestra:", "locked": "El ZIP descargable contiene únicamente el ACG ficticio de Neko. Los datos de clientes, códigos de pedido y YAML original no están disponibles. El Planner y el prompt diario son vistas previas de solo lectura, no archivos del producto.", "shop": "Ver ediciones personalizadas en Etsy",
}

_DE = {
    **_EN,
    "title": "Beispielhoroskop von Chefredakteurin Neko | nanamiastro", "description": "Teste Nekos Geburtshoroskop, Planner, KI-Deutung und Astrocartography-Karte.",
    "banner": "Demoversion", "banner_body": "Dieses Beispiel nutzt die festen Daten von Chefredakteurin Neko. Nach dem Kauf kannst du deine eigene Personal Edition erstellen.",
    "eyebrow": "Nekos Beispielhoroskop", "name": "Chefredakteurin Neko", "hero": "Erkunde das nanamiastro-Erlebnis mit festen fiktiven Daten. Nichts auf dieser Seite erstellt oder verändert die Personal Edition eines Kunden.",
    "date": "22. Februar 2022 · 22:22 Uhr", "place": "Yokohama, Japan", "fictional": "Fiktive Beispieldaten", "sample_role": "Dies ist eine Kaufvorschau mit fiktiven Daten. Nekos Daten sind in keinem kostenpflichtigen Download enthalten.",
    "acg_title": "ACG Personal Edition", "acg_lead": "Erkunde Nekos Karte und Beispiel-ZIP. Das kostenpflichtige ACG Bundle enthält dein persönliches ACG und einen 12-Monats-Planner.", "try_online": "ONLINE TESTEN", "explore_acg": "Nekos ACG erkunden", "explore_acg_desc": "Sieh dir Nekos Beispiellinien vor dem Download auf der Weltkarte an.", "sample_zip": "BEISPIEL-ZIP", "zip_title": "ACG Personal Edition ZIP", "zip_desc": "Lade das deutsche Beispiel herunter und prüfe Dateien und README.",
    "planner_title": "Enthaltener 12-Monats-Planner", "planner_lead": "Vorschau des Planners, der im ACG Bundle und in der FULL Edition enthalten ist. Der eigenständige Planner ist pausiert und wird hier nicht verkauft.", "permanent_demo": "DAUERHAFTE DEMO", "planner_card": "Vorschau des 12-Monats-Planners", "planner_desc": "Jede tägliche KI-Schaltfläche und jeder QR-Code verwendet Nekos feste Demo-URL.", "open_pdf": "PDF in neuem Tab öffnen", "save_pdf": "PDF speichern", "planner_note": "Etwa 5 MB und 432 Seiten. Die Vorschau kann einen Moment zum Laden benötigen.", "daily_tag": "TÄGLICHES KI-BEISPIEL", "daily_title": "Diesen Tag mit KI deuten", "daily_desc": "Teste den schreibgeschützten täglichen Prompt, der im Planner verlinkt ist.",
    "previews_title": "Kostenlose Vorschauen", "previews_lead": "Weitere kostenlose Möglichkeiten, dieses fiktive Beispiel zu erkunden.", "available": "VERFÜGBAR", "birth_chart": "Geburtshoroskop", "birth_chart_desc": "Sieh dir Nekos Beispiel-Horoskoprad an.", "ai_page": "KI-Seite", "ai_page_desc": "Lies ein kurzes Beispiel für eine KI-Deutung.",
    "chart_tag": "BEISPIEL-GEBURTSHOROSKOP", "chart_title": "Horoskop von Chefredakteurin Neko", "chart_desc": "Ein vollständiges Horoskoprad aus den Beispieldaten.", "chart_alt": "Beispiel-Geburtshoroskop von Chefredakteurin Neko",
    "reading_tag": "BEISPIEL-KI-DEUTUNG", "reading_title": "Eine neugierige Redakteurin mit weitem Blick", "core": "Kernstimme", "core_body": "Neko erkennt Muster, verfolgt ungewöhnliche Fragen und verwandelt komplexe Ideen in eine einladende Geschichte.", "rhythm": "Kreativer Rhythmus", "rhythm_body": "Eigenständiges Erkunden gelingt am besten im Gleichgewicht mit ruhiger Beobachtung und spielerischen Pausen.", "growth": "Entwicklungsthema", "growth_body": "Das Beispiel deutet auf Lernen durch neue Orte, Perspektiven und kreative Werkzeuge hin.", "sample_disclaimer": "Dies ist ein fiktiver redaktioneller Beispieltext, keine persönliche Beratung und keine Tatsachendeutung über ein reales Tier oder einen Menschen.",
    "locked_title": "Nur Beispiel:", "locked": "Das herunterladbare ZIP enthält ausschließlich Nekos fiktives ACG-Beispiel. Kundendaten, Bestellcodes und rohe YAML-Downloads bleiben unzugänglich. Planner und Tagesprompt sind schreibgeschützte Kaufvorschauen, keine Produktdateien.", "shop": "Personalisierte Editionen auf Etsy ansehen",
}


def get_neko_demo_ui(lang: str) -> dict[str, str]:
    return {"ja": _JA, "en": _EN, "es": _ES, "de": _DE}.get(lang, _EN)
